- name: openconfig-platform
  docs:
    - yang/platform/openconfig-platform.yang
    - yang/platform/openconfig-platform-types.yang
    - yang/platform/openconfig-platform-transceiver.yang
  build:
    - yang/platform/openconfig-platform.yang
    - yang/platform/openconfig-platform-transceiver.yang
  run-ci: true