- name: openconfig-system-wifi-ext.yang
  docs:
    - wifi/system/openconfig-system-wifi-ext.yang
    - system/openconfig-system.yang
  build:
    - wifi/system/openconfig-system-wifi-ext.yang
  run-ci: true
