- name: openconfig-types
  docs:
    - yang/openconfig-types.yang
    - yang/types/openconfig-yang-types.yang
    - yang/types/openconfig-inet-types.yang
  build:
    - yang/openconfig-types.yang
    - yang/types/openconfig-yang-types.yang
    - yang/types/openconfig-inet-types.yang
  run-ci: false