// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: p4/tmp/p4config.proto

#include "p4/tmp/p4config.pb.h"
#include "p4/tmp/p4config.grpc.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/channel_interface.h>
#include <grpc++/impl/codegen/client_unary_call.h>
#include <grpc++/impl/codegen/method_handler_impl.h>
#include <grpc++/impl/codegen/rpc_service_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/sync_stream.h>
namespace p4 {
namespace tmp {

}  // namespace p4
}  // namespace tmp

